### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by MatRouault** [MarioGiancini/Genesis-Super-Customizer#1]
Great plugin, thanks a lot for sharing !
I have this message in my dashboard after activation, though

Notice: Undefined index: default in /Applications/MAMP/htdocs/yoursitename/wp-content/plugins/genesis-super-customizer/public/class-gsc-base.php on line 174

Any suggestion ?
M

**Comment by MarioGiancini** [comment]
Awesome! Thanks so much for trying out Genesis Super Customizer. It’s a work in progress but I think it has some real potential.

I’ll take look into the issue.

Tell me which plugins you’re using and which theme. This plugin is designed to work well with Genesis parent theme and custom child themes, but support for the premium child themes isn’t there yet,

Thanks.

-Mario
@MarioGiancini http://twitter.com/MarioGiancini
I  Amplify  Creators.

**Comment by MatRouault** [comment]
Hello Mario,
Thank for your qucik reply.
Yes, your plugin has a real potential, there's no doubt on that !
I'm using Genesis Sample Theme. I have deactivated all my plugins but the message still appears. (The customizer doesn't work.)
Thanks.

**Comment by MarioGiancini** [comment]
I can't seem to replicate it on my end using WordPress versions 4.1 until 4.2.2. 

Have you tried using it just with Genesis parent theme? It may be that something in your child theme, a custom class, clashing with the GSC Base Class. Line 174 is referring the the first instance of "self".

**Comment by MatRouault** [comment]
Hello Mario,

Using MAMP, all plugins deactivated, with Genesis parent theme, the error message remains.
' Notice: Undefined index: default in /Applications/MAMP/htdocs/mysitename/wp-content/plugins/genesis-super-customizer/public/class-gsc-base.php on line 174'
Strange that you can't replicate this error...

I'd love to use your plugin !

Mat

**Comment by MarioGiancini** [comment]
Hey Mat,

So I've tried it on XAMPP and MAMP on my Mac, thinking maybe it's because of a local host issue, but I still can't replicate that error.

Have you tried it on a staging site online somewhere? Also, it's been updated a couple times this week. Could possible have fixed the fluke error.
